// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheGame.Infrastructure.Persistence.Users;

#nullable disable

namespace TheGame.Infrastructure.Persistence.Users.Migrations
{
    [DbContext(typeof(UserDataDbContext))]
    [Migration("20260714110743_EnablePlayerOptimisticConcurrency")]
    partial class EnablePlayerOptimisticConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HashIterations")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique();

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_hash_iterations", "HashIterations > 0");
                        });
                });

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.DataMigrationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("data_migrations", (string)null);
                });

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.PlayerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("players", null, t =>
                        {
                            t.HasCheckConstraint("ck_players_experience", "experience >= 0");

                            t.HasCheckConstraint("ck_players_level", "level >= 1");

                            t.HasCheckConstraint("ck_players_money", "money >= 0");

                            t.HasCheckConstraint("ck_players_revision", "revision >= 0");
                        });
                });

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.PlayerItemEntity", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId", "ItemId");

                    b.ToTable("player_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_items_kind", "Kind IN (0, 1)");
                        });
                });

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.PlayerLoadoutEntity", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmorItemId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponItemId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("player_loadouts", (string)null);
                });

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.PlayerEntity", b =>
                {
                    b.HasOne("TheGame.Infrastructure.Persistence.Users.AccountEntity", "Account")
                        .WithOne("Player")
                        .HasForeignKey("TheGame.Infrastructure.Persistence.Users.PlayerEntity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.PlayerItemEntity", b =>
                {
                    b.HasOne("TheGame.Infrastructure.Persistence.Users.PlayerEntity", "Player")
                        .WithMany("Items")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.PlayerLoadoutEntity", b =>
                {
                    b.HasOne("TheGame.Infrastructure.Persistence.Users.PlayerEntity", "Player")
                        .WithOne("Loadout")
                        .HasForeignKey("TheGame.Infrastructure.Persistence.Users.PlayerLoadoutEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.AccountEntity", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("TheGame.Infrastructure.Persistence.Users.PlayerEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Loadout");
                });
#pragma warning restore 612, 618
        }
    }
}
